/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jiuyan_faiss_NativeClient */

#ifndef _Included_com_jiuyan_faiss_NativeClient
#define _Included_com_jiuyan_faiss_NativeClient
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    test
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jiuyan_faiss_NativeClient_test
  (JNIEnv *, jclass);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexFlatL2_index
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_com_jiuyan_faiss_NativeClient_indexFlatL2_1index
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexFlatL2_add
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_indexFlatL2_1add
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexFlatL2_train
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_indexFlatL2_1train
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexFlatL2_search
 * Signature: (JI[FI[F[J)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_indexFlatL2_1search
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jint, jfloatArray, jlongArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    close
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexIVFFlat_index
 * Signature: (JIII)J
 */
JNIEXPORT jlong JNICALL Java_com_jiuyan_faiss_NativeClient_indexIVFFlat_1index
  (JNIEnv *, jclass, jlong, jint, jint, jint);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexIVFFlat_train
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_indexIVFFlat_1train
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexIVFFlat_add
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_indexIVFFlat_1add
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexIVFFlat_add_with_ids
 * Signature: (JI[F[J)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_indexIVFFlat_1add_1with_1ids
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jlongArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    setProbe
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_setProbe
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexIVFFlat_search
 * Signature: (JI[FI[F[J)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_indexIVFFlat_1search
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jint, jfloatArray, jlongArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexIVFPQ_index
 * Signature: (JIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_jiuyan_faiss_NativeClient_indexIVFPQ_1index
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexIVFPQ_train
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_indexIVFPQ_1train
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexIVFPQ_add
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_indexIVFPQ_1add
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    setPQProbe
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_setPQProbe
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    indexIVFPQ_search
 * Signature: (JI[FI[F[J)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_indexIVFPQ_1search
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jint, jfloatArray, jlongArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    StandardGpuResources
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jiuyan_faiss_NativeClient_StandardGpuResources
  (JNIEnv *, jclass);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    GpuIndexFlatConfig
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_jiuyan_faiss_NativeClient_GpuIndexFlatConfig
  (JNIEnv *, jclass);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    GpuIndexFlatL2_index
 * Signature: (JIJ)J
 */
JNIEXPORT jlong JNICALL Java_com_jiuyan_faiss_NativeClient_GpuIndexFlatL2_1index
  (JNIEnv *, jclass, jlong, jint, jlong);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    GpuIndexFlatL2_add
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_GpuIndexFlatL2_1add
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    GpuIndexFlatL2_search
 * Signature: (JI[FI[F[J)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_GpuIndexFlatL2_1search
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jint, jfloatArray, jlongArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    setGpuIVFProbe
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_setGpuIVFProbe
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    GpuIndexIVFFlat_index
 * Signature: (JIJZIIII)J
 */
JNIEXPORT jlong JNICALL Java_com_jiuyan_faiss_NativeClient_GpuIndexIVFFlat_1index
  (JNIEnv *, jclass, jlong, jint, jlong, jboolean, jint, jint, jint, jint);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    GpuIndexIVFFlat_train
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_GpuIndexIVFFlat_1train
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    GpuIndexIVFFlat_add
 * Signature: (JI[F)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_GpuIndexIVFFlat_1add
  (JNIEnv *, jclass, jlong, jint, jfloatArray);

/*
 * Class:     com_jiuyan_faiss_NativeClient
 * Method:    GpuIndexIVFFlat_search
 * Signature: (JI[FI[F[J)I
 */
JNIEXPORT jint JNICALL Java_com_jiuyan_faiss_NativeClient_GpuIndexIVFFlat_1search
  (JNIEnv *, jclass, jlong, jint, jfloatArray, jint, jfloatArray, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
